---

- name: Remove tower project
  tower_project:
    name: "cfme-ansible"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove tower project
  tower_project:
    name: "openshift-ansible-contrib"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove tower project
  tower_project:
    name: "ansible-redhat-access-insights-client"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove tower organization
  tower_organization:
    name: "Default"
    description: "Set to Default since the trial license only allows one organization. You can change it if you have deep pockets"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

