---
- job_template: vmw-setup
  success_nodes:
  - job_template: vmw-nfs
    success_nodes:
    - job_template: vmw-prod
      success_nodes:
      - job_template: vmw-haproxy
        success_nodes:
        - job_template: vmw-ocp-install
          success_nodes:
          - job_template: vmw-ocp-configure
            success_nodes:
            - job_template: vmw-ocp-demo
