---
- hosts: storage
  gather_facts: yes
  become: no
  vars_files:
  - vars/main.yaml
  roles:
  - rhsm
  - vmware-guest-setup
  - cloud-provider-setup
  - docker-storage-setup
  - openshift-volume-quota
  - gluster-ports
