---
- hosts: localhost
  roles:
    - create-vm-haproxy

- name: Deploy ha proxy server
  hosts: haproxy
  roles:
    - rhsm
    - vmware-guest-setup
  ignore_errors: yes

- name: Configure ha proxy server
  hosts: haproxy
  roles:
    - haproxy-server

- name: Configure ha proxy server files
  hosts: haproxy, masters, infras
  roles:
    - haproxy-server-config

- name: Configure ha proxy server files
  hosts: haproxy
  roles:
    - keepalived_haproxy
