---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  roles:
  - create-vm-cns-prod-ose

- hosts: glusterfs 
  gather_facts: yes
  become: no
  roles:
  - rhsm
  - vmware-guest-setup
  - cloud-provider-setup
  - docker-storage-setup
  - openshift-volume-quota
  - gluster-ports
