---
- name: fulfill OSE3 prerequisites on production hosts roles
  hosts: localhost
  roles:
    - create-vm-prod-ose

- name: fulfill OSE3 prerequisites on production hosts roles
  hosts: nodes 
  roles:
    - rhsm
    - vmware-guest-setup
    - cloud-provider-setup
    - docker-storage-setup
    - openshift-volume-quota
  ignore_errors: yes
