---
- hosts: localhost
  user: root
  become: false
  ignore_errors: yes
  tasks:
    - name: snapshot all added VMs
      vmware_guest_snapshot:
        hostname: "{{ openshift_cloudprovider_vsphere_host }}"
        username: "{{ openshift_cloudprovider_vsphere_username }}"
        password: "{{ openshift_cloudprovider_vsphere_password }}"
        validate_certs: False
        name: "{{ hostvars[item].vm_name }}"
        datacenter: "{{ openshift_cloudprovider_vsphere_datacenter }}"
        folder: "{{ openshift_cloudprovider_vsphere_datacenter }}/vm/{{ openshift_cloudprovider_vsphere_folder }}"
        state: present
        snapshot_name: ss
      with_items: 
      - "{{ groups['nodes'] }}"
