---

- name: Remove workflow-ocp-vmw-install
  command: tower-cli workflow delete --name="workflow-ocp-vmw-install"

- name: Remove vmw-ocp-demo template
  tower_job_template:
    name: vmw-ocp-demo
    job_type: run
    project: openshift-ansible-contrib
    playbook: "ocp-demo.yaml"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove vmw-ocp-configure template
  tower_job_template:
    name: vmw-ocp-configure
    job_type: run
    project: openshift-ansible-contrib
    playbook: "ocp-configure.yaml"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove vmw-ocp-install template
  tower_job_template:
    name: vmw-ocp-install
    job_type: run
    project: openshift-ansible-contrib
    playbook: "ocp-install.yaml"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove vmw-haproxy template
  tower_job_template:
    name: vmw-haproxy
    job_type: run
    project: openshift-ansible-contrib
    playbook: "haproxy.yaml"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove vmw-prod template
  tower_job_template:
    name: vmw-prod
    job_type: run
    project: openshift-ansible-contrib
    playbook: "prod.yaml"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove vmw-nfs template
  tower_job_template:
    name: vmw-nfs
    job_type: run
    project: openshift-ansible-contrib
    playbook: "nfs.yaml"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove vmw-setup template
  tower_job_template:
    name: vmw-setup
    job_type: run
    project: openshift-ansible-contrib
    playbook: "setup.yaml"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"








- name: Remove tower group
  tower_group:
    name: vmw
    inventory: "vmw-inventory"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove tower inventory
  tower_inventory:
    name: "vmw-inventory"
    organization: "Default"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove tower credential for machine
  tower_credential:
    name: vmw-privkey
    kind: ssh
    organization: "Default"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove tower credential for vmw
  tower_credential:
    name: vmw
    state: absent
    kind: vmware
    organization: "Default"
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove tower project
  tower_project:
    name: "openshift-ansible-contrib"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove tower project
  tower_project:
    name: "ansible-redhat-access-insights-client"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove tower project
  tower_project:
    name: "cfme-ansible"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: Remove tower organization
  tower_organization:
    name: "Default"
    description: "Set to Default since the trial license only allows one organization. You can change it if you have deep pockets"
    state: absent
    tower_config_file: "~/.tower_cli.cfg"

- name: subscription-manager unregister
  command: subscription-manager unregister
  become: true

